# Generated by Django 2.1 on 2019-02-12 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190212_0957'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friendlink',
            options={'ordering': ['join_time']},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['?']},
        ),
        migrations.AlterField(
            model_name='friendlink',
            name='join_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
