# Generated by Django 2.1 on 2019-02-11 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(default='nameless', max_length=32, verbose_name='昵称')),
                ('username', models.CharField(max_length=32, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='邮箱')),
                ('gender', models.IntegerField(choices=[(1, '男'), (0, '女')], default=0, verbose_name='性别')),
                ('presentation', models.CharField(blank=True, default='你好，陌生人', max_length=240, null=True, verbose_name='个人说明')),
                ('avatar', models.ImageField(default='/media/avatar/HP.jpg', upload_to='media/avatar', verbose_name='头像')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='注册时间')),
            ],
        ),
    ]
