# Generated by Django 2.1 on 2019-02-11 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('useradmin', '0001_initial'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('article', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_comments', to='blog.Article')),
                ('deliver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comments', to='useradmin.UserInfo')),
                ('reply', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_replies', to='comment.Comment')),
            ],
            options={
                'ordering': ['-create_time'],
            },
        ),
    ]
